dist: bionic

language: bash

services:
  - docker

git:
  submodules: false

before_install:
  - echo -e "machine github.com\n  login $GIT_USER\n  password $GIT_PW > ~/.netrc
  - git submodule set-url msg-rpc https://github.com/flotte-goes-smart/msg-rpc.git
  - git submodule init
  - git submodule update
script:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PW" https://flotte-docker-registry.spdns.org/
  - docker build -t flotte-user-managment .
  - docker tag flotte-user-managment flotte-docker-registry.spdns.org/flotte-user-managment
  - docker push flotte-docker-registry.spdns.org/flotte-user-managment:latest