name: Build Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Copy Repo Files
        uses: actions/checkout@master

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Login to Portus
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.PORTUS_USERNAME }}
          password: ${{ secrets.PORTUS_PASSWORD }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            flotte-docker-registry.spdns.org/flotte-user-managment:latest
            ghcr.io/flotte-meets-hwr-db/flotte-user-management/user-management-server